# Generated by Django 6.0.3 on 2026-04-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='seller',
            name='password',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
