# Generated by Django 6.0.3 on 2026-04-13 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customer_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='mainapp.customer'),
        ),
    ]
